const userController = require('../controllers/user.controller')

app.get('/verify-old-user', userController.verifyOldUser)
app.sendadd('/send-address',userController.sendadd)
app.sendOtp('/send-otp',userController.sendOtp)
app.verifyOtp('/verify-otp-fp',userController.verifyOtp)
app.forgetpass('/forgot-password',userController.forgetpass)
app.resetpass('/reset-password',userController.resetpass)
app.vOtp('/verify-otp',userController.vOtp)
app.getImage('/get-image',userController.getImage)
app.login('/login',userController.login)
app.addLand('/add-land',userController,addLand)
app.getland('/get-land',userController,getland)
app.getAllLands('/get-land-all',userController,getAllLands)
app.sellland('/sell-land',userController,sellland)
app.buyland('/buy-land',userController,buyland)
app.logout('/logout',userController.logout)
app.buyReq('/buy-req',userController.buyReq)
app.registerreq('/register-req',userController,registerreq)
app.registeraccept('/register-accept',userController.registeraccept)
app.buyaccept('/buyer-accept',userController.buyaccept)
app.reject('/register-reject',userController.reject)
app.buyerrej('/buyer-reject',userController.buyerrej)